apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nestjs-demo-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/longnt267/ws-argocd-gitops.git
    targetRevision: main
    path: helm/nestjs-demo-chart
    helm:
      valueFiles:
        - values.yaml
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: nestjs-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
