# values-dev.yaml - chỉ khai báo những gì KHÁC so với values.yaml mặc định

env: dev
replicaCount: 1

image:
  tag: dev-71f0314

service:
  port: 4000
  nodePort: 31160

resources:
  requestCpu: 50m
  requestMemory: 64Mi
  limitCpu: 200m
  limitMemory: 256Mi
